import PDFDocument from "pdfkit";

interface FinanceSummaryData {
  workspaceName: string;
  generatedAt: string;
  totalInvoiced: number;
  totalPaid: number;
  totalOutstanding: number;
  invoices: Array<{
    number: string;
    client: string;
    amount: number;
    status: string;
    dueDate: string;
  }>;
}

interface ContractSummaryData {
  contractNumber: string;
  title: string;
  agency: string;
  status: string;
  startDate: string;
  endDate: string;
  totalValue: number;
  clins: Array<{
    number: string;
    description: string;
    quantity: number;
    unitPrice: number;
    total: number;
  }>;
  keyPersonnel: Array<{
    name: string;
    role: string;
  }>;
  modifications: Array<{
    number: string;
    description: string;
    amount: number;
    date: string;
  }>;
}

interface CapabilityStatementData {
  title: string;
  companyOverview: string;
  coreCompetencies: string;
  pastPerformance: string;
  naicsCodes: string;
  certifications: string;
  contactInfo: string;
}

function formatCurrency(amount: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
  }).format(amount);
}

export function generateFinanceSummaryPDF(data: FinanceSummaryData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // Header
    doc.fontSize(20).font("Helvetica-Bold").text("Finance Summary Report", { align: "center" });
    doc.moveDown(0.5);
    doc.fontSize(10).font("Helvetica").text(`${data.workspaceName} | Generated: ${data.generatedAt}`, { align: "center" });
    doc.moveDown(1.5);

    // Summary cards
    doc.fontSize(14).font("Helvetica-Bold").text("Overview");
    doc.moveDown(0.5);
    doc.fontSize(11).font("Helvetica");
    doc.text(`Total Invoiced: ${formatCurrency(data.totalInvoiced)}`);
    doc.text(`Total Paid: ${formatCurrency(data.totalPaid)}`);
    doc.text(`Outstanding: ${formatCurrency(data.totalOutstanding)}`);
    doc.moveDown(1.5);

    // Invoice table
    if (data.invoices.length > 0) {
      doc.fontSize(14).font("Helvetica-Bold").text("Invoices");
      doc.moveDown(0.5);

      // Table header
      const tableTop = doc.y;
      const colWidths = [80, 120, 80, 80, 80];
      const headers = ["Invoice #", "Client", "Amount", "Status", "Due Date"];
      doc.fontSize(9).font("Helvetica-Bold");
      let xPos = 50;
      headers.forEach((header, i) => {
        doc.text(header, xPos, tableTop, { width: colWidths[i] });
        xPos += colWidths[i];
      });

      doc.moveDown(0.5);
      doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
      doc.moveDown(0.3);

      // Table rows
      doc.font("Helvetica").fontSize(9);
      data.invoices.forEach((inv) => {
        const rowY = doc.y;
        if (rowY > 700) {
          doc.addPage();
        }
        xPos = 50;
        doc.text(inv.number || "—", xPos, doc.y, { width: colWidths[0] });
        const currentY = doc.y - 11;
        doc.text(inv.client || "—", xPos + colWidths[0], currentY, { width: colWidths[1] });
        doc.text(formatCurrency(inv.amount), xPos + colWidths[0] + colWidths[1], currentY, { width: colWidths[2] });
        doc.text(inv.status, xPos + colWidths[0] + colWidths[1] + colWidths[2], currentY, { width: colWidths[3] });
        doc.text(inv.dueDate || "—", xPos + colWidths[0] + colWidths[1] + colWidths[2] + colWidths[3], currentY, { width: colWidths[4] });
        doc.moveDown(0.3);
      });
    }

    // Footer
    doc.moveDown(2);
    doc.fontSize(8).font("Helvetica").fillColor("#666666").text("This report was generated by PrimeContractorOS. All amounts are in USD.", { align: "center" });

    doc.end();
  });
}

export function generateContractSummaryPDF(data: ContractSummaryData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // Header
    doc.fontSize(20).font("Helvetica-Bold").text("Contract Summary", { align: "center" });
    doc.moveDown(0.5);
    doc.fontSize(12).font("Helvetica").text(data.title, { align: "center" });
    doc.moveDown(1.5);

    // Contract details
    doc.fontSize(14).font("Helvetica-Bold").text("Contract Details");
    doc.moveDown(0.5);
    doc.fontSize(11).font("Helvetica");
    doc.text(`Contract Number: ${data.contractNumber}`);
    doc.text(`Agency: ${data.agency}`);
    doc.text(`Status: ${data.status}`);
    doc.text(`Period of Performance: ${data.startDate} — ${data.endDate}`);
    doc.text(`Total Value: ${formatCurrency(data.totalValue)}`);
    doc.moveDown(1.5);

    // CLINs
    if (data.clins.length > 0) {
      doc.fontSize(14).font("Helvetica-Bold").text("Contract Line Items (CLINs)");
      doc.moveDown(0.5);
      doc.fontSize(9).font("Helvetica");
      data.clins.forEach((clin) => {
        doc.font("Helvetica-Bold").text(`CLIN ${clin.number}: ${clin.description}`);
        doc.font("Helvetica").text(`  Qty: ${clin.quantity} | Unit Price: ${formatCurrency(clin.unitPrice)} | Total: ${formatCurrency(clin.total)}`);
        doc.moveDown(0.3);
      });
      doc.moveDown(1);
    }

    // Key Personnel
    if (data.keyPersonnel.length > 0) {
      doc.fontSize(14).font("Helvetica-Bold").text("Key Personnel");
      doc.moveDown(0.5);
      doc.fontSize(10).font("Helvetica");
      data.keyPersonnel.forEach((person) => {
        doc.text(`${person.name} — ${person.role}`);
      });
      doc.moveDown(1);
    }

    // Modifications
    if (data.modifications.length > 0) {
      doc.fontSize(14).font("Helvetica-Bold").text("Modifications");
      doc.moveDown(0.5);
      doc.fontSize(9).font("Helvetica");
      data.modifications.forEach((mod) => {
        doc.font("Helvetica-Bold").text(`Mod ${mod.number}: ${mod.description}`);
        doc.font("Helvetica").text(`  Amount: ${formatCurrency(mod.amount)} | Effective: ${mod.date}`);
        doc.moveDown(0.3);
      });
    }

    doc.end();
  });
}

export function generateCapabilityStatementPDF(data: CapabilityStatementData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // Header with blue bar
    doc.rect(0, 0, 612, 80).fill("#1e40af");
    doc.fontSize(22).font("Helvetica-Bold").fillColor("#ffffff").text(data.title || "Capability Statement", 50, 30, { align: "center" });
    doc.moveDown(3);

    // Company Overview
    doc.fillColor("#000000");
    if (data.companyOverview) {
      doc.fontSize(14).font("Helvetica-Bold").text("Company Overview");
      doc.moveDown(0.3);
      doc.fontSize(10).font("Helvetica").text(data.companyOverview);
      doc.moveDown(1);
    }

    // Core Competencies
    if (data.coreCompetencies) {
      doc.fontSize(14).font("Helvetica-Bold").text("Core Competencies");
      doc.moveDown(0.3);
      doc.fontSize(10).font("Helvetica").text(data.coreCompetencies);
      doc.moveDown(1);
    }

    // Past Performance
    if (data.pastPerformance) {
      doc.fontSize(14).font("Helvetica-Bold").text("Past Performance");
      doc.moveDown(0.3);
      doc.fontSize(10).font("Helvetica").text(data.pastPerformance);
      doc.moveDown(1);
    }

    // NAICS & Certifications side by side
    if (data.naicsCodes || data.certifications) {
      doc.fontSize(14).font("Helvetica-Bold").text("Codes & Certifications");
      doc.moveDown(0.3);
      doc.fontSize(10).font("Helvetica");
      if (data.naicsCodes) doc.text(`NAICS Codes: ${data.naicsCodes}`);
      if (data.certifications) doc.text(`Certifications: ${data.certifications}`);
      doc.moveDown(1);
    }

    // Contact Information
    if (data.contactInfo) {
      doc.fontSize(14).font("Helvetica-Bold").text("Contact Information");
      doc.moveDown(0.3);
      doc.fontSize(10).font("Helvetica").text(data.contactInfo);
    }

    doc.end();
  });
}
